databases:
  - name: apiloomi
    databaseName: apiloomi
    user: apiloomi

services:
  - type: web
    name: apiloomi
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn apiloomi.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: apiloomi
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: POETRY_VERSION
        value: 1.7.0