# Generated by Django 4.2 on 2023-10-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0003_remove_filme_avaliacao_alter_filme_estrelas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Roteirista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='filme',
            name='atores',
            field=models.ManyToManyField(blank=True, related_name='filmes_atuados', to='filmes.ator'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='diretores',
            field=models.ManyToManyField(blank=True, related_name='filmes_dirigidos', to='filmes.diretor'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='roteiristas',
            field=models.ManyToManyField(blank=True, related_name='filmes_escritos', to='filmes.roteirista'),
        ),
    ]
