# Generated by Django 4.2 on 2023-11-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('filmes', '0005_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(related_name='usuarios', to='auth.group'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$KHt5vANNMFcQy5P8iitAZU$WUlz04GDy3etlH8mwPkBSlnlwgq3mJHftuf63XLXHUE=', max_length=128),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(related_name='usuarios_permissions', to='auth.permission'),
        ),
        migrations.RemoveField(
            model_name='filme',
            name='atores',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='diretores',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='generos',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='roteiristas',
        ),
        migrations.DeleteModel(
            name='Ator',
        ),
        migrations.DeleteModel(
            name='Diretor',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.DeleteModel(
            name='Roteirista',
        ),
        migrations.AddField(
            model_name='filme',
            name='atores',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='diretores',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='generos',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='roteiristas',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
    ]
