# Generated by Django 4.2 on 2023-11-04 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filmes', '0006_delete_status_remove_usuario_usuario_usuario_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filme',
            name='atores',
            field=models.CharField(blank=True, default='', max_length=320, null=True),
        ),
        migrations.AlterField(
            model_name='filme',
            name='diretores',
            field=models.CharField(blank=True, default='', max_length=320, null=True),
        ),
        migrations.AlterField(
            model_name='filme',
            name='generos',
            field=models.CharField(blank=True, default='', max_length=320, null=True),
        ),
        migrations.AlterField(
            model_name='filme',
            name='roteiristas',
            field=models.CharField(blank=True, default='', max_length=320, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$iVy2TdLD0ZzkUW23aUq0ml$yfwWgzQDkhvuaTZ35X/W7rJdXe9bqmgv51R0PImxNzs=', max_length=128),
        ),
    ]
