# Generated by Django 4.2.7 on 2023-11-09 20:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0009_usuario_can_create_filme_usuario_can_delete_filme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$UVimdrx0bdh8VPyQy0S7EG$C+yGorqebmnq9D1WckB4WlwqXk4jLGivG3/DU0IDEQ4=', max_length=128),
        ),
    ]
