# Generated by Django 4.2.7 on 2023-11-14 21:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0010_usuario_uuid_alter_usuario_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.AddField(
            model_name='filme',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='filme',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmes', to='filmes.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$dATHPhNHWSwxeVqmkuWJON$v6qbEyv5Wzr/nf9GGtrD246wv72QLDieHIaEqkzkWJE=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
