# Generated by Django 4.2.7 on 2023-11-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0011_remove_usuario_email_filme_uuid_usuario_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
